## server configuration
server:
  port: 8003
spring:
  application:
    name: manager
  shutdown:
    enable: true
  profiles:
    active: dev
  kafka:
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: movie-seat
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
      - myCache
    caches:
      myCache:
        ttl: 600 # TTL in seconds (adjust as needed)
data service:
  openapi:
    dev-url: http://localhost:9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
shows:
  seats:
    exchange: seatsInventory
    exchange.queue: seatsInventoryQueue
theatres:
  exchange:
      name: theatre_exchange
      queue: theatre_exchange_queue
bms:
  onboard:
    API_KEY: TestAPIKey
logging:
  level:
    com:
      bms: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
---



## Dev Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:manager
   # url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: sa
    initialization-mode: always
   # initialize: true
   # platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---

## SVT Profile
spring:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  config:
    activate:
      on-profile: svt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms_onboard
    username: root
    password: LGcnsg@123
    initialization-mode: always
    data: data.sql
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
